### ISSUE TITLE
Get whole set of queried data instead of one

### ISSUE THREAD

**Issue by nadunindunil** [christian-fei/Simple-Jekyll-Search#104]
Hi,
This is a nice plugin and a life saviour.
I have come across specific requirement like filtered data from search need to be categorized. As an example [https://devhints.io/](https://devhints.io/).
is there any way I can achieve this instead of using `searchResultTemplate` for one result.

**Comment by nadunindunil** [comment]
hi @christian-fei ,
yes I did with a little bit of change in the algo where HTML element creates 😄

**Comment by christian-fei** [comment]
Great!
