### ISSUE TITLE
online guide out dated

### ISSUE THREAD

**Issue by marabesi** [christian-fei/Simple-Jekyll-Search#107]
The guide available at https://christianfei.com/posts/Use-Simple-Jekyll-Search-on-your-blog-in-these-easy-steps is outdated. The json properties for example are not compatible with the latest version of the lib.

I am not sure if is possible to edit it directly in github.

**Comment by christian-fei** [comment]
Hey @marabesi ,
here you can edit it in case: https://github.com/christian-fei/christian-fei.github.io/blob/master/posts/2017-02-05-Use-Simple-Jekyll-Search-on-your-blog-in-these-easy-steps.md

Thank you very much for the heads up :)

**Comment by marabesi** [comment]
https://github.com/christian-fei/christian-fei.github.io/pull/6
