### ISSUE TITLE
Implementation work on local, but not on Github pages, search.json in both root and _site

### ISSUE THREAD

**Issue by joshjacobson** [christian-fei/Simple-Jekyll-Search#110]
@christian-fei @scottmathson thanks for helping look into this.

This is me 're-opening' #103 

_Originally posted by @joshjacobson in https://github.com/christian-fei/Simple-Jekyll-Search/issues/103#issuecomment-443470452_

**Comment by JackGruber** [comment]
Have you tried to update your _config.yml (baseurl) as described in the last post?

**Comment by joshjacobson** [comment]
@JackGruber Search.json no longer throws a 404
