### ISSUE TITLE
Is there any way to exclude certain values, such as spaces, from working in search?

### ISSUE THREAD

**Issue by ekfuhrmann** [christian-fei/Simple-Jekyll-Search#111]
I have multiple pages that have spaces within their name resulting in anything having a space showing up in the results. Ideally I'd want search to ignore space values.

**Comment by JackGruber** [comment]
In the last version spaces are used as separator for search multiple words. 
For this reason, blanks should be ignored for search.

Have you an example?

**Comment by christian-fei** [comment]
@ekfuhrmann I believe it’s because your site is hosted under `/jekyll-gulp`, resulting in a 404 for `/search.json` (it should be `/jekyll-gulp/search.json`.
Try to set this explicitly when invoking SimpleJekyllSearch

**Comment by ekfuhrmann** [comment]
I moved the JS inline in order to leverage Jekyll's `relative_url`, but the problem still persists even with the JSON now pointing to `/jekyll-gulp/search.json`.

###`search.html`
```html
<!-- Html Elements for Search -->
<div id="search-container">
<input type="text" id="search-input" placeholder="search...">
<ul id="results-container"></ul>
</div>

<script src="https://cdn.rawgit.com/christian-fei/Simple-Jekyll-Search/master/dest/simple-jekyll-search.min.js" type="text/javascript"></script>

<script>
const search = document.getElementById('search-input');

if (search) {
  SimpleJekyllSearch({
    searchInput: search,
    resultsContainer: document.getElementById('results-container'),
    json: "{{ './search.json' | relative_url }}",
    searchResultTemplate: '<li><a href="{url}">{heading}</a></li>'
  });
}
</script>
```

**Comment by christian-fei** [comment]
@ekfuhrmann did you find a way of getting this to work?

**Comment by ekfuhrmann** [comment]
@christian-fei yeah, by moving the JS inline, I was able to use `relative_url` and get it working. As mentioned though, the only issue I seem to run into with Search is that using a **space** seems to return EVERY result containing a space within its title. Not a huge deal, but really the only issue I've now come across with it.
