### ISSUE TITLE
I set the `searchInput` but it can't work.

### ISSUE THREAD

**Issue by Desgard** [christian-fei/Simple-Jekyll-Search#113]
![image](https://user-images.githubusercontent.com/7804535/50670298-a0ca3c80-1005-11e9-8bde-9d610990d02d.png)

**Comment by christian-fei** [comment]
@Desgard just checking in: did you find a solution?

**Comment by Desgard** [comment]
> @Desgard just checking in: did you find a solution?

I can't find the reason. And I use the `onclick` property to run my logic. It can work. 🤣
