### ISSUE TITLE
Multiple search.json files

### ISSUE THREAD

**Issue by smrpr** [christian-fei/Simple-Jekyll-Search#114]
I have a multilanguage Jekyll site and 2 different search pages, one per language.

Their HTML code is exactly the same except for the strings, which are translated:

```
---
layout: home
title: Search
comments: false
locale: en
---

<article>
    <div style="text-align: center">
        <h3>{{ site.data.search.en.header }}</h3>
        <input type="text" id="search-input" class="search-input" placeholder="Search"/>
    </div>
    <h3>{{ site.data.search.en.results }}</h3>
    <ul id="results-container">
    </ul>
</article>

<script type="text/javascript">

    window.onload = function(){
        new SimpleJekyllSearch({
            searchInput: document.getElementById('search-input'),
            resultsContainer: document.getElementById('results-container'),
            json: '{{site.url}}/search_en.json',
            searchResultTemplate: '<li class="entry-title"><a href="{url}" title="{title}">{{site.data.common.flags.{{locale}}}} - {title}</a></li>'
        });
    }

</script>
```

As you see, the `json` parameter specifies a `search_en.json` that I tweaked to only show results in the english locale:

```
---
---
[
  {% for post in site.posts  %}
    {% if post.locale  == 'en' %}
      {
        "title"    : "{{ post.title | escape }}",
        "category" : "{{ post.category }}",
        "tags"     : "{{ post.tags | join: ', ' }}",
        "url"      : "{{ site.url }}{{ post.url }}",
        "date"     : "{{ post.date }}",
        "locale"   : "{{ post.locale }}"
      } {% unless forloop.last %},{% endunless %}
    {% endif %}
  {% endfor %}
]
```

I created another one at the project root called search_es.json which does the same but in Spanish.

Although the spanish search page (located at /search) works well, the english one (/en/search) doesn't.

Chrome JS console shows this error when loading the page:

```
Uncaught Error: SimpleJekyllSearch --- failed to get JSON
```

I can't see what I'm doing wrong since the two files are exactly the same except for the if condition. Is it not possible to have different search.json files with different conditions in each of them?

Thanks

**Comment by marcelocesar** [comment]
Hi, @smrpr 

1. Execute command "jekyll doctor" and verify exists error.
2. Check the metadata in the post file, they should be the same in the search.json file.

Example:

post.markdown:
```
---
title
category
tags
url
---
```


search.json
```
[
  {% for post in site.posts %}
    {
      "title"    : "{{ post.title | escape }}",
      "category" : "{{ post.category }}",
      "tags"     : "{{ post.tags | join: ', ' }}",
      "url"      : "{{ site.baseurl }}{{ post.url }}"
    } {% unless forloop.last %},{% endunless %}
  {% endfor %}
]
```
These steps worked for me. I hope it can help you.

**Comment by 3noki** [comment]
Hi @marcelocesar 

I am having the same issue with this, I tried your example above and still getting the error;

`Uncaught Error: SimpleJekyllSearch --- failed to get JSON (/index.html/search.json)`

The only thing I get in jekyll doctor is;
```
jekyll doctor
Configuration file: C:/Users/user/Desktop/github/repo/_config.yml
       Jekyll Feed: Generating feed for posts
         AutoPages: Disabled/Not configured in site.config.

Pagination: Complete, processed 1 pagination page(s)
           Warning: Your site URL does not seem to be absolute, check the value of `url` in your config file.
```


What are you setting for the url or base url in config.yml?
