### ISSUE TITLE
Search not working for me, what am I doing wrong?

### ISSUE THREAD

**Issue by probonopd** [christian-fei/Simple-Jekyll-Search#115]
Thanks for SimpleJekyllSearch, looks like it is exactly what's needed to get a simple search going on GitHub Pages.

However, SimpleJekyllSearch does not work for me on http://appimage.github.io/.

What am I doing wrong?
https://appimage.github.io/search.json is there...

**Comment by marcelocesar** [comment]
@probonopd 

1. Execute command "jekyll doctor" and verify exists error.
2. Check the metadata in the post file, they should be the same in the search.json file.

Example:

post.markdown:
```
---
title
category
tags
url
---
```


search.json
```
[
  {% for post in site.posts %}
    {
      "title"    : "{{ post.title | escape }}",
      "category" : "{{ post.category }}",
      "tags"     : "{{ post.tags | join: ', ' }}",
      "url"      : "{{ site.baseurl }}{{ post.url }}"
    } {% unless forloop.last %},{% endunless %}
  {% endfor %}
]
```
These steps worked for me. I hope it can help you.

**Comment by probonopd** [comment]
Thanks @marcelocesar. Do you know whether it is possible to run `jekyll doctor` in a GitHub Pages setup?

Again, https://appimage.github.io/search.json is there... and it's valid JSON seemingly.

**Comment by marcelocesar** [comment]
Sorry. I do not know. I believe this is not possible.
