### ISSUE TITLE
templateMiddleware is not getting called on search match

### ISSUE THREAD

**Issue by rameshsunkara** [christian-fei/Simple-Jekyll-Search#119]
### What am I trying to do ?
 - Show my search container if there are any results in other words do something based on the fact that there are search results

### My Code
```
 SimpleJekyllSearch({
        searchInput: document.getElementById('blog-search-input'),
        resultsContainer: document.getElementById('blog-results-container'),
        json: "search.json",
        searchResultTemplate: '<li><a href="{url}" title="{title}" class="bold">{title}</a></li>',
        templateMiddleware: function () {
            console.log('Search is working fine, I want this method to be called when there are any results');
            console.log(document.getElementById('search-results'));
        }
    })
```

**Comment by lynn9388** [comment]
@rameshsunkara I test your options about `templateMiddleware` in my blog, and it works fine.

<img width="1918" alt="Screen Shot 2019-06-04 at 4 54 18 PM" src="https://user-images.githubusercontent.com/6847317/58865628-7b8f4680-86e9-11e9-8c94-40d0b8753bbc.png">
