### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by JaimeObregon** [christian-fei/Simple-Jekyll-Search#120]
Sorry if this might have an obvious response but, **is there a Changelog or "Release notes"**?

I have a site in production running 1.6.2 and I would love to know if it would be worth, risky or require changes in the site to update it to 1.7.2 (latest).

**Comment by christian-fei** [comment]
Hello @JaimeObregon ,

sorry for the late response.

There isn't an official changelog unfortunately,
but to have more info you could check out [the diff here](https://github.com/christian-fei/Simple-Jekyll-Search/compare/v1.6.2...v1.7.2)

There are no breaking changes though, so it should be safe to upgrade
