### ISSUE TITLE
Search in blog post content

### ISSUE THREAD

**Issue by agardnerIT** [christian-fei/Simple-Jekyll-Search#124]
Hi, I've forked `reverie` and I'm wondering how I enable search within blog post content?

It seem to only search the blog title (or perhaps front matter) at present.

Is it possible to do a full text search or is that an enhancement request?

**Comment by JackGruber** [comment]
Hi,

https://github.com/christian-fei/Simple-Jekyll-Search/wiki#enabling-full-text-search

**Comment by agardnerIT** [comment]
Thanks for the hint. Due to misformatted JSON my search was breaking.

For others looking to solve this, the search bar builds it's results from the `search.json` file which is at `https://yoursite.github.io/reverie/search.json`. Feed the output of that into a JSON parser like `jsonlint` and see where the error is.

I fixed my issue by adding a `content` field into the JSON which pointed to `post.content` then cleaning it up:

```
---
---
[
  {% for post in site.posts %}
    {

      "title"    : "{% if post.title != "" %}{{ post.title | strip_html | strip_newlines | escape }}{% else %}{{ post.excerpt | strip_html | strip_newlines | escape }}{%endif%}",
      "excerpt"  : "{% if post.excerpt != "" %}{{ post.excerpt | strip_html | strip_newlines | escape }} {% endif %}",
      "url"      : "{{ site.baseurl }}{{ post.url }}",
      "category" : "{{ post.categories | join: ', '}}",
      "tags"     : "{{ post.tags | join: ', ' }}",
      "date"     : "{{ post.date | date: "%d/%m/%Y" }}",
      "content"  : "{{ post.content | strip_html | strip_newlines | escape}}"
    } {% unless forloop.last %},{% endunless %}
  {% endfor %}
]
```

**Comment by davidlinhl** [comment]
I would like to add a little bit to the discussion. In my blog, I noticed \ and tab can also corrupt json. Thus I further removed \ and tab in the post content.
`      "content"  : "{{ post.content | strip_html | strip_newlines | escape | remove: '\'| replace:  "	", ' ' }}"
`
and it all worked well.

**Comment by christian-fei** [comment]
Thanks!
