### ISSUE TITLE
Results are displayed locally but not online

### ISSUE THREAD

**Issue by Funeoz** [christian-fei/Simple-Jekyll-Search#125]
So the script is working when I run my website locally. But when I push my changes to Github, the results from the search aren't displayed. Here is the page with the search engine: [https://funeoz.github.io/techlovers/search/](https://funeoz.github.io/techlovers/search/l) and the repo:
[https://github.com/Funeoz/techlovers](https://github.com/Funeoz/techlovers)

Also getting this in Firefox console: **ReferenceError: SimpleJekyllSearch is not defined**

(PS: I know that it was already asked but can't really see the issue.)

**Comment by christian-fei** [comment]
hello,

i think that you're not loading the `simple-jekyll-search.js` file correctly (or at all) on your site.

i will look into the repo you linked at get back to  you

**Comment by Funeoz** [comment]
It works fine now. Thank you !

**Comment by christian-fei** [comment]
super, +1 for using it in a creative way!

thank you
