### ISSUE TITLE
ReferenceError: SimpleJekyllSearch is not defined

### ISSUE THREAD

**Issue by AlexMussell** [christian-fei/Simple-Jekyll-Search#129]
Hey. I am receiving the above error and was wondering if you could help point me in the right direction? I have read through the other similar issues, but I no fixes have sorted it.

``` javascript
>>> assets/js/search-script.js

SimpleJekyllSearch({
  searchInput: document.getElementById('search-input'),
  resultsContainer: document.getElementById('results-container'),
  json: '/search.json',
})
```

``` json
>>> example from _site/search.json, showing search.json is working:

    {

      "title"    : "test",
      "url"      : "/python/2019/03/23/welcome-to-jekyll.html",
      "category" : "Python",
      "tags"     : "",
      "date"     : "2019-03-23 15:33:36 +0000",
      "discription" : ""

    } 
  
]
```

``` html
>>> _layouts/blog.html

---
layout: default
---

{%- if page.title -%}
  <h1 class="page-heading">{{ page.title }}</h1>
{%- endif -%}

{{ content }}

{%- if site.posts.size > 0 -%}
  <ul class="base-layout">
    <li>
      <h1 id="page-label">Blog</h1>
    </li>

    <div id="search-container">
      <input type="text" id="search-input" placeholder="search...">
      <ul id="results-container"></ul>
    </div>
    

    {%- for post in site.posts -%}

    BLAH BLAH ETC POST FORMATTING
    {%- endfor -%}
  </ul>

<script src="/assets/js/search-script.js" type="text/javascript"></script>
```

To install I did `npm init`, `npm install simple-jekyll-search`

Any advice would be greatly appreciated.

**Comment by christian-fei** [comment]
hello,

please try to use the CDN with: 

```
<script src="https://unpkg.com/simple-jekyll-search/dest/simple-jekyll-search.min.js"></script>
```

does the script `/assets/js/search-script.js` exist ?

**Comment by AlexMussell** [comment]
Okay so using the cdn seems to have resolved the issue you bloody legend. Im new to NPM so I probably did something wrong. Thanks for the help man!

**Comment by AlexMussell** [comment]
But maybe one last tip? When you search, it updates as you search. However, when you go back to an empty text field, all posts don't show up again.  If you dont have the time, im sure ill work it out. But a pointer would be great. Shall this logic be done in liquid templating or in js?

**Comment by christian-fei** [comment]
@AlexMussell hey, glad it worked out!

i don't quite understand your issue

**Comment by AlexMussell** [comment]
Sorry I'll try to explain better. So I have a `blog.html` which renders the list of all posts. (Which after my update to implement search, contains the search input box and results container)
```javascript
---
layout: default
---

{%- if page.title -%}
  <h1 class="page-heading">{{ page.title }}</h1>
{%- endif -%}

{{ content }}

  <ul class="base-layout">
    <li>
      <h1 id="page-label">Blog</h1>
    </li>

    <div id="search-container">
      <input type="text" id="search-input" placeholder="search...">
    </div>
    
    <ul id="results-container">

      {%- for post in site.posts -%}
        <li>
              HTML FOR EACH POST
        </li>
      {%- endfor -%}
      </ul>
    </ul>
  </ul>
</ul>

<script src="https://unpkg.com/simple-jekyll-search/dest/simple-jekyll-search.min.js"></script>
<script src="/assets/js/search-script.js" type="text/javascript"></script>
```

So when you first go onto the page, all posts are rendered. Then, when I try to search for specific posts, it replaces the list of all posts with the found posts. However, when I then empty the search-input, the list of all posts does not render. It just renders nothing. Essentially, when the input is empty, i want to return all posts. Any advice would be appreciated.
