### ISSUE TITLE
success() does not behave as a callback

### ISSUE THREAD

**Issue by Glassheart83** [christian-fei/Simple-Jekyll-Search#130]
Looking at the documentation [HERE](https://github.com/christian-fei/Simple-Jekyll-Search/wiki#success-function-optional) I read that `success` function should be fired once the data is loaded, and then it should be accessible to trigger search programmatically.

But it's not.
The error lies on line 61 of `index.js`

```js
function initWithJSON (json) {
    options.success(json)
    repository.put(json)
    registerInput()
}
```

we can see the `success` function is fired before any useful init operation, and not after them.

Moreover, in order to follow the callback pattern, `success` should be fired with the `this` context of `
SimpleJekyllSearch` and should accept no data or processed data, which is not the case.

I may work on a PR during next days if necessary.

**Comment by christian-fei** [comment]
hello @Glassheart83 ! if you could make a PR that would be great!
