### ISSUE TITLE
Showing more than 10 searched items

### ISSUE THREAD

**Issue by hy38** [christian-fei/Simple-Jekyll-Search#133]
Hi! I'm very pleased to apply this search function to my page!

All the features works fine.

However, I wish to make the number of searched items be shown more than 10.

There might be 2 options I guess..

1. show all of the items in one page.

2. seperate items in several pages.(like post pagination)

Since this search function works realtime not with queries, I guess option 1 would be fine!

Can you let me know which code(or variable) to fix to show all the items in one page?

Thanks for your function anyway :)

**Comment by JackGruber** [comment]
Hi,

use the [limit](https://github.com/christian-fei/Simple-Jekyll-Search/wiki#limit-number-optional) option.

```
<script>
SimpleJekyllSearch({
  searchInput: document.getElementById('search-input'),
  resultsContainer: document.getElementById('results-container'),
  json: '/search.json',
  searchResultTemplate: '<li><a href="{{ site.url }}{url}">{title}</a></br>{info}</br>{preview}</br></br></li>',
  noResultsText: 'Sorry no search result',
  limit: 999,
})
</script>
```

**Comment by hy38** [comment]
Thanks a lot! It worked just right for me.

I guess I missed looking for [wiki](https://github.com/christian-fei/Simple-Jekyll-Search/wiki#limit-number-optional). Sorry for my carelessness.

**Comment by christian-fei** [comment]
@hy38 glad it worked! I think the wiki link must be made more visible..

**Comment by christian-fei** [comment]
thanks @JackGruber for stepping in!
