### ISSUE TITLE
Fix known vulnerabilities

### ISSUE THREAD

**Issue by SkypLabs** [christian-fei/Simple-Jekyll-Search#136]
Hi,

Your project contains a couple of known vulnerabilities due to its dependencies: [npm-audit.json.txt](https://github.com/christian-fei/Simple-Jekyll-Search/files/4359192/npm-audit.json.txt)

Could you please upgrade the dependencies in question to fix the security issues?

Let me know if I can be of any help.

Thank you.

**Comment by christian-fei** [comment]
hi @SkypLabs , thanks you for the interest!
i fixed the known security vulnerabilities by removing the package-lock.json file.
now @dependabot is fine with the repo

**Comment by SkypLabs** [comment]
Thanks @christian-fei for your great reactivity!

However, are you sure it is the right thing to do? By removing the lock file, you won't freeze your dependencies nor the dependencies of your dependencies. Isn't it better to just upgrade the lock file?

In all cases, a new release is needed to have an effect on third-party projects using your package as a dependency.

**Comment by christian-fei** [comment]
thanks for the heads up @SkypLabs 

included back the package-lock.json file and created a new tag soon to be published by the CI

**Comment by SkypLabs** [comment]
Awesome!

Thanks again :+1:

**Comment by christian-fei** [comment]
PS: `npm-check`

maybe this issue is perhaps of an unneeded dep found by `npm-check`, namely `browser-pack-flat`.
removed it and published another one
