### ISSUE TITLE
error on chrome use by jekyll blog

### ISSUE THREAD

**Issue by jxnu-liguobin** [christian-fei/Simple-Jekyll-Search#139]
error info
simple-jekyll-search.min.js:6 Uncaught TypeError: Cannot read property 'call' of undefined
    at w.SimpleJekyllSearch (simple-jekyll-search.min.js:6)
    at HTMLDocument.<anonymous> (autoloader.js:13)
w.SimpleJekyllSearch @ simple-jekyll-search.min.js:6
(anonymous) @ autoloader.js:13

my load js
`
---
    layout: null
---
  document.write('<input id="search-input" placeholder="{{ site.sidebar.simple_jekyll_search.placeholder }}" />');
document.write('<div id="results-container"></div>');
document.write('<script src="{{ site.sidebar.simple_jekyll_search.src }}"></script>');
function loadStyle(url) {
  var link = document.createElement('link');
  link.rel = 'stylesheet';
  link.href = url;
  var head = document.getElementsByTagName('head')[0];
  head.appendChild(link);
}
loadStyle('{{ site.sidebar.simple_jekyll_search.stylesheet }}');
document.addEventListener("DOMContentLoaded", function () {
  SimpleJekyllSearch({
    json: '{{ site.sidebar.simple_jekyll_search.json }}',
    searchInput: document.getElementById('search-input'),
    resultsContainer: document.getElementById('results-container')
  });
});
`

my json
`
---
layout: null
---
[
  {% if site.sidebar.simple_jekyll_search.enable %}
  {% for post in site.posts %}
    {
      "title"    : "{{ post.title | escape }}",
      "category" : "{{ post.category }}",
      "tags"     : "{{ post.tags | join: ', ' }}",
      "url"      : "{{ site.baseurl }}{{ post.url }}",
      "date"     : "{{ post.date }}"
    } {% unless forloop.last %},{% endunless %}
  {% endfor %}
  {% endif %}
]
`

**Comment by arnelap** [comment]
The Firefox version of this error is
TypeError: t.success is undefined in simple-jekyll-search.min.js:6:4184

Corresponding error when not minified:
_Firefox:_ TypeError: _options.success is undefined
_Chrome:_ bUncaught TypeError: Cannot read property 'call' of undefined
 in simple-jekyll-search.js:358:5


It's looking for the function to call on success, but that function is optional.

Temporary workaround: Add empty Success function to the options,   success: function(){}

`    var sjs = SimpleJekyllSearch({
  searchInput: document.getElementById('search-input'),
  resultsContainer: document.getElementById('results-container'),
  json: '/search.json',
  success: function(){}
})`

**Comment by arnelap** [comment]
so replace 
`_options.success.call(search) `
with something like 
 ` if(_options.success !== undefined) { _options.success.call(search) }`
in simple-jekyll-search.js:358

**Comment by arnelap** [comment]
just noticed this is a duplicate of https://github.com/christian-fei/Simple-Jekyll-Search/issues/137

cheers :)

**Comment by jxnu-liguobin** [comment]
thank you

> just noticed this is a duplicate of #137
> 
> cheers :)

**Comment by christian-fei** [comment]
thank you @arnelap  @jxnu-liguobin
