### ISSUE TITLE
[BUG REPORT] Cannot read property 'search' of undefined

### ISSUE THREAD

**Issue by fsuaterdogan** [christian-fei/Simple-Jekyll-Search#142]
I am typing and results are not showing. It says:
![image](https://user-images.githubusercontent.com/48383007/79051677-2f326280-7c3a-11ea-9c9d-d6acbca0519c.png)
![image](https://user-images.githubusercontent.com/48383007/79051680-348fad00-7c3a-11ea-9e29-6241b14149be.png)

Everythink is on my "base" page.
My repo: https://github.com/fsuaterdogan/help-tourhunter-com

**Comment by christian-fei** [comment]
Hello,

thanks for your interest, will look into it when I find some time!

**Comment by AndersonTheThird** [comment]
I can confirm but I don't receive any errors. Search function is broken.

**Comment by adelivet** [comment]
@christian-fei When do you think you could fix this issue?

**Comment by christian-fei** [comment]
@fsuaterdogan on which website where can I reproduce this? 

on https://help.tourhunter.com/ everything seems fine
