### ISSUE TITLE
Wrong version v1.7.4 instead of v1.7.7 in release zip file

### ISSUE THREAD

**Issue by N7K4** [christian-fei/Simple-Jekyll-Search#143]
In the `dest` folder of release v1.7.7 zip-file, there is a `simple-jekyll-search.min.js` file which holds the version v1.7.4 and the release has the version v1.7.7, there is a mismatch. The copyright is 2020, seams to be up to date.

**Comment by christian-fei** [comment]
Hello,

thanks for you interest, will look into it when I find some time!

**Comment by christian-fei** [comment]
Should be fine now, thank you.
release 1.7.8
