### ISSUE TITLE
Is there a way to order the results by date?

### ISSUE THREAD

**Issue by iigkid** [christian-fei/Simple-Jekyll-Search#145]
I am not well versed in javascript and have been searching the web for examples of the options you present in the Wiki.

For example:
exclude -- I put it in  SimpleJekyllSearch({ as " exclude: 'Articles written', })
but this does not work. I am trying to exclude the results that come up with Articles Written by... I'm not sure what the correct format is and for multiple exclusions.

fuzzy -- "fuzzy: true, " this doesn't seem to work very well and gives a myriad of answers. Have I done something wrong?

Is there a way to order results by date published? or {{ page.date }}

I really appreciate your help. I have implemented this on my test site but need to get it working well now. 

https://13549566-review-137-resear-de6nr4.staging.mexicoinsuranceonline.com/search.html

**Comment by christian-fei** [comment]
Hello,
please with the options:

```javascript
{
  exclude: ['Articles written']
}
```

You should sort the search items in your `search.json` if possible.

Alternatively, you can use the option `sortMiddleware` as [described here](https://github.com/christian-fei/Simple-Jekyll-Search/wiki#sortmiddleware-function-optional)
