### ISSUE TITLE
Uncaught TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by Matir** [christian-fei/Simple-Jekyll-Search#146]
This may be the same as closed #141, but since the reporter of that closed it without a lot of detail, I'm reporting separately.

When configuring as shown in the documentation with 1.7.7, I get the following:

> Uncaught TypeError: Cannot read property 'call' of undefined
>    at w.SimpleJekyllSearch (simple-jekyll-search.min.js:6)
>    at HTMLDocument.<anonymous> (search.js:4)

My configuration is:

```
document.addEventListener("DOMContentLoaded", function(event){
  var searchInput = document.getElementById('searchQuery');
  if (searchInput) {
    var sjs = SimpleJekyllSearch({
      searchInput: searchInput,
      resultsContainer: document.getElementById('searchResults'),
      json: '/index.json'
    });
  }
});
```

I believe this is due to commit 6fceffe4a08a60aa16a143681eeed61128b5ae5d.  It appears that the original `_options` is being used for the call to the `success` callback, rather than the merged `options` object within the `simpleJekyllSearch` function.  Providing an empty function in options is a successful workaround:

```
document.addEventListener("DOMContentLoaded", function(event){
  var searchInput = document.getElementById('searchQuery');
  if (searchInput) {
    var sjs = SimpleJekyllSearch({
      searchInput: searchInput,
      resultsContainer: document.getElementById('searchResults'),
      json: '/index.json',
      success: () => {}
    });
  }
});
```

**Comment by christian-fei** [comment]
Thank you!
