### ISSUE TITLE
Latest release shown on Github is not the actual latest version

### ISSUE THREAD

**Issue by sylhare** [christian-fei/Simple-Jekyll-Search#148]
When looking for the latest release, I see:

<img width="308" alt="image" src="https://user-images.githubusercontent.com/20642750/87063729-bd3bcc00-c1dc-11ea-96db-0bc461aebd7f.png">

which show v1.0.8 from august 2015:

<img width="785" alt="image" src="https://user-images.githubusercontent.com/20642750/87063791-cd53ab80-c1dc-11ea-9c38-5a9b7e3a985c.png">

I believe that's because the newer version where not "published" using the github release but only tagged. You can still find the latest one when you click the "+37 releases" but it feels a bit misleading.
If you want, you can publish a new release by clicking on "Draft a new release" then put the right tag and finally publish. 

It's just as a FYI 🙊

**Comment by sylhare** [comment]
Also it seems the latest version is 1.7.7 but on the [simple-jekyll-search.min.js](https://github.com/christian-fei/Simple-Jekyll-Search/blob/v1.7.7/dest/simple-jekyll-search.min.js) it's written 1.7.4

So now I am wondering if the min.js file is version v1.7.4 or v1.7.7 with a typo.

**Comment by christian-fei** [comment]
This should be solved now, thank you
