### ISSUE TITLE
HTML5 Input Type=Search clear event not clearing results

### ISSUE THREAD

**Issue by nikduvall** [christian-fei/Simple-Jekyll-Search#149]
When using an HTML5 Input type="search" element, when the 'X' icon is cleared, this is not automatically clearing the results.

You can detect this with a Search event:

https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/search_event

**Comment by christian-fei** [comment]
Please make a PR @nikduvall

**Comment by nikduvall** [comment]
[PR #150](https://github.com/christian-fei/Simple-Jekyll-Search/pull/150) created.
