### ISSUE TITLE
Sort search results by the number of times the input search term appears in full-text page searches?

### ISSUE THREAD

**Issue by amanchadha** [christian-fei/Simple-Jekyll-Search#151]
Hi!

Great work with Simple-Jekyll-Search. Its a life-saver!

I'm using full-text searches for my Jekyll pages as indicated in the [wiki](https://github.com/christian-fei/Simple-Jekyll-Search/wiki#enabling-full-text-search). 

I'd like to make a feature request to sort search results by the number of times the input search term appears in each Jekyll page/post indexed within `search.json`. 

This would make the most "relevant" results (measured by the number of times the input term appears on a particular page, as a metric) pop up first.

Sorry if this request has already been made - tried looking for it, but couldn't find it.

Thanks Christian and folks for the awesome work!

Aman

**Comment by christian-fei** [comment]
Hello @amanchadha , thanks for the interest and the kind words!
If you would like to open a PR, that would be greatly appreciated
