### ISSUE TITLE
favor title matches over full content matches?

### ISSUE THREAD

**Issue by covener** [christian-fei/Simple-Jekyll-Search#153]
When using the full-text search, it would be nice if title matches were pushed to the top of the results.

**Comment by amanchadha** [comment]
I agree with this ask. This would definitely boost the utility of Simple Jekyll Search, with some not-so-intrusive changes.

**Comment by christian-fei** [comment]
i'll give it a try if i find some time!

**Comment by amanchadha** [comment]
@christian-fei  @covener 

The TF-IDF concept is usually used to solve these kinds of issues so just sending some inputs your way in case this might help -- [here's](https://github.com/George3d6/tf-idf) a quick Javascript implementation of TF-IDF that we can use as baseline.
