### ISSUE TITLE
cann't build search.json indexes

### ISSUE THREAD

**Issue by AmbroseRen** [christian-fei/Simple-Jekyll-Search#157]
I have to write indexes for myself,and zhe discription need to copy my all article in lt,I think is very worse feel.Can you complete them,
I will continues attention.

**Comment by christian-fei** [comment]
Hello @AmbroseRen , I don't understand what you mean

**Comment by AmbroseRen** [comment]
it is means how to build zhe indexes for my website,these haven't tools to craw zhe indexes for my site.
