### ISSUE TITLE
(minor) wiki footer fix

### ISSUE THREAD

**Issue by Kolossi** [christian-fei/Simple-Jekyll-Search#163]
In the wiki repo https://github.com/christian-fei/Simple-Jekyll-Search.wiki.git, can you delete "_Footer.md"? - it's causing the wierd text crashing into the bottom of the wiki page :-)

**Comment by christian-fei** [comment]
done, thanks

**Comment by Kolossi** [comment]
Somehow, for me at least, the wiki page is now completely broken :-(  Maybe the _Footer.md must exist but be empty?

**Comment by christian-fei** [comment]
you are right! whaattt??
Trying to figure out what's going on

**Comment by christian-fei** [comment]
I have no clue what's going on.
the markdown seems valid.
after saving a minor change the wiki shows up correctly, but after a refresh it's messed up again.
i guess it's a temporary issue with the github wiki?

**Comment by christian-fei** [comment]
"Fixed" it by moving all relevant information from the Wiki to the Readme..

**Comment by Kolossi** [comment]
Glad you found a way, shame the wiki seemed to bomb out though.
