### ISSUE TITLE
Facing issue: SimpleJekyllSearch --- failed to get JSON

### ISSUE THREAD

**Issue by satheesh-mallow** [christian-fei/Simple-Jekyll-Search#165]
@all 

I am facing SimpleJekyllSearch --- failed to get JSON issue only in this project. I didn't know why it is happening. 
<img width="1252" alt="Screenshot 2021-03-15 at 2 24 46 PM" src="https://user-images.githubusercontent.com/14173227/111128073-86ebf300-859a-11eb-89e4-1e3cd2734caf.png">
I have also checked the network tab, the file response is 200 but still I am getting above issue. 
<img width="1389" alt="Screenshot 2021-03-15 at 2 24 59 PM" src="https://user-images.githubusercontent.com/14173227/111128175-9b2ff000-859a-11eb-87d0-31ab50f61d1e.png">

**Code:**
```
<script src="https://unpkg.com/simple-jekyll-search@latest/dest/simple-jekyll-search.min.js"></script>

<input type="text" id="search-input" placeholder="Search blog posts..">
<ul id="results-container"></ul>
<script>
    $(document).ready(function(){
        var sjs = SimpleJekyllSearch({
            searchInput: document.getElementById('search-input'),
            resultsContainer: document.getElementById('results-container'),
            json: 'http://127.0.0.1:4000/search.json'
        })
        });
</script>
```

**Comment by christian-fei** [comment]
Hello @satheesh-mallow ,
you could try to use a relative path for the "/search.json"

```
            json: 'http://127.0.0.1:4000/search.json'
```

If you have a public repo or link I can take a quick look.

**Comment by satheesh-mallow** [comment]
@christian-fei 

Have tried that, I have found the issue. There is a unexpected character `\` where placed in the json file.
