### ISSUE TITLE
Markdown files can break json

### ISSUE THREAD

**Issue by b3cking** [christian-fei/Simple-Jekyll-Search#168]
Hey, Chris!

If a md file (post) contains special chars (e.g. backslash in this particular case), the generated json breaks, which also breaks the whole searching function.

Example data in MD: "c:\windows\system32\drivers\etc\hosts"
In generated JSON: invalid escape char error.

![screen](https://user-images.githubusercontent.com/4153430/114320789-eeed1500-9b17-11eb-9e55-82225da675be.png)

**Comment by christian-fei** [comment]
Hello!

Did you perhaps follow the instructions here? https://github.com/christian-fei/Simple-Jekyll-Search#if-search-isnt-working-due-to-invalid-json

This could solve your issue.

**Comment by b3cking** [comment]
Thank you, somehow I missed that part. Have a nice day!

**Comment by christian-fei** [comment]
No problem, you too @b3cking !
