### ISSUE TITLE
jekyll-multiple-languages-plugin compatibility

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [christian-fei/Simple-Jekyll-Search#169]
> Plugin: [jekyll-multiple-languages-plugin](https://github.com/kurtsson/jekyll-multiple-languages-plugin)

I am using both and I am having problems related to simple-jekyll-search can't get the current language correctly.

For example, in the json I added:

```
...
      "language" : "{{ site.lang }}",
...
```

And it is always getting the `en` value when the rest of the site is in `es`. Is there a workaround?

**Comment by christian-fei** [comment]
Hello,
sorry I have no idea. Most likely it's a setting in the language plugin you're using
