### ISSUE TITLE
Doesn't like double quotes in code highlighter

### ISSUE THREAD

**Issue by mike-jimbob-smith** [christian-fei/Simple-Jekyll-Search#173]
Search works perfectly until I add a post that has "" in the highlight block.

Changing them to single quotes restores functionality.

`scripts.js:6 Uncaught Error: SimpleJekyllSearch --- failed to get JSON (/search.json)
    at o (scripts.js:6)
    at scripts.js:6
    at XMLHttpRequest.<anonymous> (scripts.js:6)`

Search is called like so, this is unedited from a third-party theme called joseph.

`SimpleJekyllSearch({
    searchInput: document.getElementById("js-search-input"),
    resultsContainer: document.getElementById("js-results-container"),
    json: "/search.json",
    searchResultTemplate: '{article}',
    noResultsText: '<h3 class="no-results">No results found</h3>'
  });`

I am running it on Jekyll 4.2.0 with Simple-Jekyll-Search v1.6.0

**Comment by christian-fei** [comment]
hello

try this https://github.com/christian-fei/Simple-Jekyll-Search#if-search-isnt-working-due-to-invalid-json
