### ISSUE TITLE
SimpleJekyllSearch --- failed to get JSON (/search.json)

### ISSUE THREAD

**Issue by Funeoz** [christian-fei/Simple-Jekyll-Search#174]
I tried to use your script but I get this error with both minified and not minified script. I also tried to validate the json : it's valid. I can see the JSON file in the requests tab in the browser.

My `search.html` file : 

```html

---
layout: page
title: Search
---

<script src="https://unpkg.com/simple-jekyll-search@latest/dest/simple-jekyll-search.min.js"></script>
<script>
    SimpleJekyllSearch({
        searchInput: document.getElementById('searchInput'),
        resultsContainer: document.getElementById('resultsContainer'),
        json: '/search.json',
        searchResultTemplate: '<li><a href="{url}" title="{desc}">{title}</a></li>',
        noResultsText: 'No results found',
        fuzzy: false,
    })
</script>

<div class="field has-addons">
    <div class="control is-expanded">
        <input id="searchInput" class="input is-primary" type="text" placeholder="Find an article">
    </div>
</div>

<div id="resultsContainer">

</div>
```

My `search.json` file (in root directory)  :

```json
---
---
[
  {% for post in site.posts %}
  {
    "title"    : "{{ post.title | strip_html | escape }}",
    "url"      : "{{ site.baseurl }}{{ post.url }}",
    "category" : "{{ post.categories | join: ', '}}",
    "tags"     : "{{ post.tags | join: ', ' }}",
    "date"     : "{{ post.date }}",
    "description" : "{{ post.description | strip_html | strip_newlines | escape }}"
  } {% unless forloop.last %},{% endunless %}
  {% endfor %}
]
```

**Comment by kamil-adam** [comment]
You should start with
```
---
layout: null
---
```

**Comment by Funeoz** [comment]
It still doesn't work.

**Comment by Mabbs** [comment]
You can verify the generated JSON file first

**Comment by Funeoz** [comment]
The JSON file is also correct. I've verified it with https://jsonlint.com.

**Comment by Erven2016** [comment]
> The JSON file is also correct. I've verified it with https://jsonlint.com.

I met this same problem, my json file also verified and is valid.

generated json file:
```json
[
    {
      "title"    : "Welcome to Jekyll!",
      "category" : "jekyllupdate",
      "url"      : "/jekyll/update/2021/07/23/welcome-to-jekyll.html",
      "date"     : "2021-07-23 22:07:02 +0800"
    } 
  
]
```

**Comment by Mabbs** [comment]
> > The JSON file is also correct. I've verified it with https://jsonlint.com.
> 
> I met this same problem, my json file also verified and is valid.
> 
> generated json file:
> ```json
> [
>     {
>       "title"    : "Welcome to Jekyll!",
>       "category" : "jekyllupdate",
>       "url"      : "/jekyll/update/2021/07/23/welcome-to-jekyll.html",
>       "date"     : "2021-07-23 22:07:02 +0800"
>     } 
>   
> ]
> ```

This program doesn't seem to run in IE. what's your browser?

**Comment by Erven2016** [comment]
> > > The JSON file is also correct. I've verified it with https://jsonlint.com.
> > 
> > 
> > I met this same problem, my json file also verified and is valid.
> > generated json file:
> > ```json
> > [
> >     {
> >       "title"    : "Welcome to Jekyll!",
> >       "category" : "jekyllupdate",
> >       "url"      : "/jekyll/update/2021/07/23/welcome-to-jekyll.html",
> >       "date"     : "2021-07-23 22:07:02 +0800"
> >     } 
> >   
> > ]
> > ```
> 
> This program doesn't seem to run in IE. what's your browser?

The latest version of Google Chrome.

**Comment by Funeoz** [comment]
I use Firefox. I got the same problem on Brave too.

**Comment by Mabbs** [comment]
There may be a problem with the Ajax design of this program. I can import JSON manually and use it normally.
My code:  <https://github.com/Mabbs/mabbs.github.io/blob/master/search.html>

**Comment by milosmns** [comment]
Wait why was this closed? There's no official fix for it 🤔

I'm seeing the same issue, Mar 2022.
