### ISSUE TITLE
Callback when search results are displayed

### ISSUE THREAD

**Issue by jonaskohl** [christian-fei/Simple-Jekyll-Search#177]
It would be really nice if there was a callback/event which gets invoken when a search has completed and the search results (or no results) are displayed, e.g.:

```javascript
var _sjs = SimpleJekyllSearch({
  searchInput: searchInput,
  resultsContainer: resultsContainer,
  json: '/search.json',
  onSearch: function() {} // <=== This is my suggestion
});
```

**Comment by Mabbs** [comment]
I think the templateMiddleware function can do the same

**Comment by christian-fei** [comment]
this should now be available through `onSearch` as suggested by @jonaskohl
