### ISSUE TITLE
is't support search content. only support title 

### ISSUE THREAD

**Issue by ethanZhang722** [christian-fei/Simple-Jekyll-Search#183]

**Comment by ethanZhang722** [comment]
![image](https://user-images.githubusercontent.com/18411019/139254300-27473946-d8cd-4506-abf1-eb595b52e333.png)

**Comment by ethanZhang722** [comment]
@kremalicious

**Comment by Mirabis** [comment]
You need to enable "Full-text Search" https://github.com/christian-fei/Simple-Jekyll-Search#enabling-full-text-search

**Comment by ethanZhang722** [comment]
。

**Comment by y377** [comment]
@zhanghuocheng hello! 请问你搞定了吗?

**Comment by ethanZhang722** [comment]
。
