### ISSUE TITLE
Use with GitHub Pages?

### ISSUE THREAD

**Issue by pippim** [christian-fei/Simple-Jekyll-Search#186]
The installation instructions call for `npm` but I'm using GitHub Pages which doesn't allow plug-ins.

I found instructions on someone's blog that state the following requirement:

``` css
{%- include footer.html -%}

 <!-- Import SimpleJekyllSearch scripts by CDN -->
 <script
     src="https://cdn.rawgit.com/christian-fei/Simple-Jekyll-Search/master/dest/simple-jekyll-search.min.js"></script>
```

But I see no instructions in this GitHub for using CDN, which I think stands for the **C**ontent **D**elivery **N**etwork.

Is it possible to use **Simple-Jekyll-Search** with GitHub Pages? If so, are there some "simple" instructions to do so?

Thanks,

**Comment by Kolossi** [comment]
I would suggest using a GitHub pages (Jekyll) theme which already has this simple search built in - e.g. see https://github.com/amitmerchant1990/reverie

**Comment by pippim** [comment]
@Kolossi Thank you for the link. I've started reviewing the code.

**Comment by Kolossi** [comment]
You may also be interested in [my modified version of the search page](https://raw.githubusercontent.com/Kolossi/kolossi.github.io/main/_pages/search.md) from the template, the differences are:

- makes sure search box has focus on page load
- supports search query being passed in querystring (this means it can be used in e.g. a custom chrome search provider using the url template `https://kolossi.github.io/search/?%s`)

HTH
