### ISSUE TITLE
include post.content in search

### ISSUE THREAD

**Issue by AustinHay** [christian-fei/Simple-Jekyll-Search#24]
I've been using this awesome search on my website. I'd like the search to also be able to search through a post's content. Here's my search.json:

```

---
layout: null

---
[
   {% for post in site.posts %}
     {
       "title"    : "{{ post.title | escape }}",
       "category" : "{{ post.category }}",
       "tags"     : "{{ post.tags | array_to_sentence_string }}",
       "url"      : "{{ site.baseurl }}{{ post.url }}",
       "date"     : "{{ post.date }}",
       "content"  : "{{ post.content }}"
        } {% unless forloop.last %},{% endunless %}
     {% endfor %}
 ]
```

Including content disables the .js. Any clue why? Any recommended changes the .js to make it also search through the content?

Thanks!

**Comment by tibotiber** [comment]
Firstly a big thank you for putting this together :).
Met the same problem as @AustinHay, the proposed solution did not work since there were still some newlines after escaping. I got it working with:
```
"content"  : "{{ post.content | escape | strip_newlines }}"
```
It also works with this second solution which I find prettier (in terms of generated json):
```
"content"  : "{{ post.content | strip_html | strip_newlines }}"
```
Cheers.

**Comment by christian-fei** [comment]
Thank you! Would you be so kind to propose a pull request? :)

**Comment by tibotiber** [comment]
Sure but what kind of pull request? The only place I can think of adding this info is the README... Is that what you're thinking about?

**Comment by christian-fei** [comment]
Oh I see, that's true..
Thought `content` was included in the default `search.json` file.

Yes, it would be cool if you could add a section in the readme :)

**Comment by tibotiber** [comment]
Here you go! Thanks again :).
