### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by anselmh** [christian-fei/Simple-Jekyll-Search#25]
I might have missed something but is this package published to npm? Couldn’t find it in the registry but as it has a package.json and is not private I expected to find it there.

**Comment by eiriksm** [comment]
Hey. I also expected to be able to install it via npm, which I can't.

Would be nice if you could fine the time one day :)

Oh, and thanks for making this available!

**Comment by christian-fei** [comment]
Q: are there any known complications to ship non node-modules to npm?

**Comment by anselmh** [comment]
Not as far as I know. Recently the team also announced that they want to have other non node modules on the platform and in all my packages I never had an issue.

**Comment by christian-fei** [comment]
Boom https://www.npmjs.com/package/simple-jekyll-search

It would be nice to have your feedback :)

**Comment by anselmh** [comment]
Works fine, thanks a lot!

**Comment by eiriksm** [comment]
Thanks! That was fast.

FYI, it does not work for me with `require('simple-jekyll-search);`. I had to use `require('simple-jekyll-search/src');`

Does not matter a lot, as long as one remembers it :)

Thanks again!

**Comment by anselmh** [comment]
Ah, @christian-fei you should declare the main script in the `package.json` to fix that. :)

**Comment by eiriksm** [comment]
It is declared, it is only pointing to the browserify packed version. Which does not pack so well with browserify the second time (when I am requiring it) :)

If this has no specific purpose (for example for bower) I would recommend changing it to `simple-jekyll-search/src/index.js`

**Comment by christian-fei** [comment]
thanks, should be fixed with the release 1.0.2
