### ISSUE TITLE
Apply the MIT License properly

### ISSUE THREAD

**Issue by Alexander01998** [christian-fei/Simple-Jekyll-Search#27]
@christian-fei
# Problem
Currently, only a part of the MIT License is included, which is attached to the end of [README.md](https://github.com/christian-fei/Simple-Jekyll-Search#license).

Because the license is not in a LICENSE file and the copyright notice is missing, it is very hard, if not impossible, to use Simple-Jekyll-Search without violating §2 of the license:
>The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

# Recommended fix
- [x] Move the license to a LICENSE file.
- [x] Add a copyright notice at the top of the license, including:
  - [x] the name(s) of the author(s) and
  - [x] the copyright year(s)
- [ ] Add a copyright notice in [jekyll-search.js](https://github.com/christian-fei/Simple-Jekyll-Search/blob/master/jekyll-search.js) and/or other files you want to license.

**Comment by christian-fei** [comment]
Thank you, I'll set aside some time to apply your fixes! :)

**Comment by Alexander01998** [comment]
Awesome! :sparkles:
