### ISSUE TITLE
Adding images

### ISSUE THREAD

**Issue by NickSarath** [christian-fei/Simple-Jekyll-Search#30]
How does one add an image next to the text returns?

for example:

I search "Apple"

And I get the result apple and next to it an image.

**Comment by daviddarnes** [comment]
You would have to add an image path to the page or page front matter. 

Maybe have the following in your post or page:
```
---
thumbnail: "/images/post-thumbnail.jpg"
---
```
You'll need to add ```thumbnail``` into the [json file that the plugin searches through](https://github.com/christian-fei/Simple-Jekyll-Search#getting-started). 
```
"thumbnail" : "{{ post.thumbnail }}",
```
Then change the [result template to include an image](https://github.com/christian-fei/Simple-Jekyll-Search#searchresulttemplate):
```
<li>
     <a href="{url}">{title}</a>
     <a href="{url}">
          <img src="{thumbnail}"/>
     </a>
</li>
```

**Comment by christian-fei** [comment]
Thanks @daviddarnes
