### ISSUE TITLE
Rendering ascii in search results

### ISSUE THREAD

**Issue by mkoohafkan** [christian-fei/Simple-Jekyll-Search#34]
A few of my post titles have ascii code (e.g. colons `&#58;` and slashes `&#47;`), and while they render just fine in the post pages they show up as plain text in the search results. Is there any way I can modify `searchResultTemplate` to render these codes as the proper characters? Right now I'm using

`searchResultTemplate: '<li><a href="{url}" title="{desc}">{title}</a></li>'`

I presume I just need to add something to the `{title}` variable, e.g. `{ title | renderascii }` or something like that.

**Comment by christian-fei** [comment]
Hello,
thanks for reporting and using the library!
Maybe it has something to do with the [templatePattern](https://github.com/christian-fei/Simple-Jekyll-Search/blob/master/src/Templater.js#L4)

Would you mind looking into it?
That would be awesome :+1:
