### ISSUE TITLE
[bug] Error: SimpleJekyllSearch --- You must specify a json

### ISSUE THREAD

**Issue by nakoo** [christian-fei/Simple-Jekyll-Search#36]
![bug](https://cloud.githubusercontent.com/assets/4975021/8019925/b8b779c2-0ca1-11e5-98e3-89e1c1a9ad19.png)

I changed recent version updated on github and I get this error message.
My json setting is just default. Please check it.

**Comment by lengerfulluse** [comment]
I got the similar error about can't found the search.json. My search json just put in the path root. Could you please help to check it?
![simple_jekyll_search-error](https://cloud.githubusercontent.com/assets/1578404/8022722/e33e7a98-0d18-11e5-942c-af2d8a180ed3.png)

**Comment by christian-fei** [comment]
Thanks for reporting, and sorry for the inconvenience :(

Could you please post the code how you initialize the library?

**Comment by daviddarnes** [comment]
If this is related to the initialising the plugin then I might have had the same issue https://github.com/basekit/docs.basekit.com/pull/89

**Comment by nakoo** [comment]
@christian-fei: Here you go. =)

SimpleJekyllSearch({
 searchInput: document.getElementById('input'),
 resultsContainer: document.getElementById('results'),
 dataSource: '/search.json'
})

**Comment by christian-fei** [comment]
Ah i see, it seems you're missing the 'json' field (instead of dataSource).
I did a terrible job at versioning this time, will do better in the future.

https://github.com/christian-fei/Simple-Jekyll-Search#json-stringjson-required

Please let me know if it works, and sorry for the waste of time

**Comment by nakoo** [comment]
@christian-fei: Oh, I didn't notice that. Thanks =)

**Comment by daviddarnes** [comment]
@christian-fei tha'll explain why my version breaks when I update. Could this be documented somewhere for people who upgrade their version of the package?

**Comment by lengerfulluse** [comment]
@christian-fei would you please help to take a look my code? It just keep with the error of 'failed to get JSON'(as the the screenshot state above).
**Here is my javascript code**:  
<script src="/dest/jekyll-search.js" type="text/javascript"></script>
    <script type="text/javascript">
      SimpleJekyllSearch({
        searchInput: document.getElementById('search'),
        resultsContainer: document.getElementById('results-container'),
        json: '/search.json',
        searchResultTemplate: '<li><a href="{url}" title="{desc}">{title}</a></li>',
        noResultsText: 'No results found',
        limit: 10,
        fuzzy: false,
        exclude: ['Welcome']
      })
    </script>

and my css code is as following:  
           <div class="nav-search">
                <span class="search-input"><input type="text" id="search" placeholder="Article..." /></span>
                <span class="icon"><i class="fa fa-search"></i></span>
                <ul id="results-container"></ul>
            </div>

Thanks in advance!

**Comment by nakoo** [comment]
@lengerfulluse: Did you add simple_search_filter.rb file to _plugin folder?
https://github.com/christian-fei/Simple-Jekyll-Search#if-search-isnt-working-due-to-invalid-json
also check in json file to have set up 'remove_chars'.
I think the problem is occurred for setting of full-text search.

**Comment by christian-fei** [comment]
@lengerfulluse I think it's because of an invalid JSON, https://github.com/christian-fei/Simple-Jekyll-Search/blob/77c80aa73532e876453de844eb6ad22ed14b640b/src/JSONLoader.js#L14

Try to validate it here: http://jsonlint.com/

**Comment by lengerfulluse** [comment]
Wow, It did was caused by the setting of full-text search, which caused a invalid JSON.   
Cool! Thanks @nakoo and @christian-fei !

**Comment by lengerfulluse** [comment]
Sorry guys, I just found that it only work in localhost( i run `jekyll s` , and search plugin can work well on localhost:4000). Unfortunately thing is that once i put the code into online(http://t.hengwei.me), it still got the same error of **failed to get /search.json**. Even though i removed the full-text search, it still got the same error.  Do you have ever met the similar problems? Thanks in advance!

**Comment by kentoo** [comment]
First of all, thanks in advance for your code!

Here the problem still remains...
JSON is well formatted, the path is in the right place, but it still got the same error:

```
Uncaught Error: SimpleJekyllSearch --- failed to get JSON (/search.json)
```

Here the way I initialize the plugin:
```js
SimpleJekyllSearch({
  searchInput: document.getElementById('search-input'),
  resultsContainer: document.getElementById('results-container'),
  json: '/search.json'
});
```

And [this](https://margiovanni.com/search.json) is the well-formatted json... Any idea?

**Comment by una** [comment]
i'm getting the same problem, @kentoo

**Comment by kentoo** [comment]
It's true! Thanks a lot.

**Comment by christian-fei** [comment]
Thanks @una !
