### ISSUE TITLE
Own results page

### ISSUE THREAD

**Issue by maxleistner** [christian-fei/Simple-Jekyll-Search#38]
How is it possible to have a result page if hitting ENTER? Thanks! (BTW really nice Script)

**Comment by christian-fei** [comment]
Hello, I don't understand what you mean, could you please elaborate?
Thanks :)

**Comment by maximaldesign** [comment]
Hey:) I mean at the moment it is a live search. I enter my words and the results are shown instantly. I would also like to have another page like http://url.de/results where i can list all the results of my search. 

1. Enter word in search field
2. Show instant results
3. Click button or press Enter on keyboard
4. --> Go to page and show results

**Comment by daviddarnes** [comment]
I think this is one of the reasons why the plugin is made with JS as it's quite difficult to render a separate page. Unless it's `website.com#search?=term` and it inserts the results into a designated element?

**Comment by christian-fei** [comment]
That's very interesting, I think with the History api you could achieve something like this, but that's beyond the scope of this plugin I think.
Like David says, to see the  instant search results is the key feature of SimpleJekyllSearch.

What's the reasons behind your idea @maximaldesign ? UX?

**Comment by maximaldesign** [comment]
Alright I understand. My reason behind it is usability. The normal website visitor would expect to be redirected on a results page. But i think we should try it out ;)

**Comment by christian-fei** [comment]
OK, got it, let me know what solution you choose at the end!

**Comment by christian-fei** [comment]
@maximaldesign do you have any updates? :)

**Comment by GrigorM** [comment]
I built a workaround for this. I was checking the jekyll-search.js file to see how it worked and found that the results were fetched with repository.search(query). So if we could access the repository variable from our custom js file than we would get the results the same way. So this is what i did:


1. Make repository variable available in the document, by adding `window.repository = repository;` in jekyll-search.js
2. Submit the form with GET so the query words are appended in the url
3. Grab the query words from the url (as a substring of window.location.href), store them in a variable (replace the '+' with ' '), and perform the query: 
`var results = repository.search(query);`
4. At this point you have the search results in the results variable, so you display them however you want: 

```
    if(results.length>0){
      for(var i=0; i<results.length; i++){
          ...
      }
    }
```

I was having some trouble cause sometimes the results wouldn't show, but i solved it by putting the search part inside setTimeout function with a minimal delay (10 miliseconds worked for me). So:

```
    setTimeout(function(){
      var results = repository.search(query);
      if(results.length>0){
        for(var i=0; i<results.length; i++){
             ...
        }
      }
    }, 10);
```
And like this you get the search results in a separate page.
