### ISSUE TITLE
IE 9 error c00c023f

### ISSUE THREAD

**Issue by XhmikosR** [christian-fei/Simple-Jekyll-Search#49]
Hi.

We are getting a script error with IE9 in Bootstrap.

```
SCRIPT575: Could not complete the operation due to error c00c023f. 
jekyll-search.js, line 1 character 625
```

This might help: http://stackoverflow.com/questions/7287706/ie-9-javascript-error-c00c023f

**Comment by XhmikosR** [comment]
Forgot to mention, this is with version 1.0.8.

BTW, is it possible to provide an unminified build too? It would help debugging.

**Comment by christian-fei** [comment]
Hello, thanks for reporting.
Will look into this.

**Comment by christian-fei** [comment]
This is the unminified build: https://github.com/christian-fei/Simple-Jekyll-Search/blob/master/dest/jekyll-search.js

**Comment by XhmikosR** [comment]
Any luck with this?

**Comment by christian-fei** [comment]
Did you find a workaround? I didn't take the time to look into this

**Comment by XhmikosR** [comment]
I haven't had a chance to look at it either. I had forgotten about it :/

**Comment by XhmikosR** [comment]
Isn't the issue still valid though? I'll try to look at it this evening.

**Comment by christian-fei** [comment]
Ops, thought you lost interest.
Sorry, reopening the issue, feel free to open a PR if you have a fix
