### ISSUE TITLE
wish - keyboard up/down navigation against the search results

### ISSUE THREAD

**Issue by appkr** [christian-fei/Simple-Jekyll-Search#57]
Hi?

I am not sure this is related to this project though--bc it's JS thing, I hope there is such function. I tried by myself, but was not easy to me. I think this helps others too~ I you don't have plan on this thing, please close this issue immediately.

Thanks ^^/

p.s. Shame on me, uuuugly code... but my approach was,

```javascript
$('#search').on('keydown', function(e) {
  if (e.keyCode !== 38 && e.keyCode !== 40) {
    return;
  }

  var target = $('#search-results').find('li');

  if (! window.current) {
    if (target.length < 1) {
      return;
    }

    window.current = target.first();
  } else {
    window.current = (e.keyCode === 40) ? target.next().first() : target.prev().first();
  }

  window.current.get(0).focus();
});
```

**Comment by daviddarnes** [comment]
@appkr you can actually tab through the results and use shift + tab to go backwards.

**Comment by appkr** [comment]
@daviddarnes Thanks for the info. I checked it works. But people are comfortable with using up/down arrows in search box...

**Comment by daviddarnes** [comment]
@appkr that seems fair, but I don't think it needs to be in the main code as it forces these controls onto everyone. Others might be using up and down for different controls.

**Comment by appkr** [comment]
@daviddarnes That sounds reasonable. I'll need to dig more to make it work. Thanks.

**Comment by christian-fei** [comment]
Thanks @appkr and @daviddarnes !
When I find some time I may look into this and see what we can do to get this to work

**Comment by appkr** [comment]
@christian-fei Thanks~ Anyway I did it by myself. 

Still I think having this functionality (as an opt-in) helps people like me.

```javascript
SimpleJekyllSearch({keyboardNavigation: true});
```

My implementation was so naive and dirty but ... for your/other's reference.

```javascript
// ...

var self = this;

$('#search').on('keydown', function(e) {
  var key = e.which;
  var target = $('#search-results').find('li');

  if ((key !== 38 && key !== 40 && key !== 13) || target.length < 1) {
    return;
  }

  // Todo. Merge nextItem() and prevItem() to navigate(direction)
  var nextItem = function() {
    if (self.selected) {
      self.selected.removeClass('active');
      var next = self.selected.next();

      if (next.length > 0) {
        self.selected = next.addClass('active');
      } else {
        self.selected = target.first().addClass('active');
      }
    } else {
      self.selected = target.first().addClass('active');
    }
  };
  var prevItem = function() {
    if (self.selected) {
      self.selected.removeClass('active');
      var prev = self.selected.prev();

      if (prev.length > 0) {
        self.selected = prev.addClass('active');
      } else {
        self.selected = target.last().addClass('active');
      }
    } else {
      self.selected = target.last().addClass('active');
    }
  };

  if (key === 40) {
    nextItem();
  } else if (key === 38) {
    prevItem();
  } else if (key === 13) {
    if (self.selected) {
      window.location.href = self.selected.find('a').attr('href');
    }
  }

  e.preventDefault();
});
```

**Comment by christian-fei** [comment]
@appkr Thank you for the idea, will work on it

**Comment by davebowker** [comment]
Up/Down in an autocomplete is pretty standard. I thought it was a bug when i tried to use it and it didn't work.

As @appkr said above, maybe have it as an option?

**Comment by damiannmm** [comment]
Hi @appkr may I ask how you implement it? I don't know where should I fork your snippet.

**Comment by appkr** [comment]
@damiannmm Since it was long time ago, i cannot remember the context at that time. Hope this link helps.
https://github.com/appkr/blog/blob/master/scripts/main.js#L197-L241
https://blog.appkr.dev/
