### ISSUE TITLE
Expose search function

### ISSUE THREAD

**Issue by HugoGiraudel** [christian-fei/Simple-Jekyll-Search#61]
It would be nice to expose the search function in order to be able to programmatically trigger the search.

**Comment by XhmikosR** [comment]
@christian-fei : isn't this fixed by https://github.com/christian-fei/Simple-Jekyll-Search/commit/a98851c97b79cf914bce516251388d2e64db53af?

**Comment by christian-fei** [comment]
You're right! Forgot to update here ^^
