### ISSUE TITLE
[bug] disappearing the results

### ISSUE THREAD

**Issue by nakoo** [christian-fei/Simple-Jekyll-Search#64]
- Version: 1.1.4 (latest)

I recently updated this script. But unlike before, this version is disappearing the results. It is occurred when I pressed arrow key to choose the page link or edit searching words. Please check this issue.

**Comment by mdlorey** [comment]
I'm having the same issue. The results show up fine, but when the enter key or directional key is pressed, the results disappear.

**Comment by christian-fei** [comment]
Hello @nakoo , @mdlorey ,

this should be fixed by now. Closing this issue, but please feel to reopen it if you're having any trouble.
