### ISSUE TITLE
Having problems with Jekyll not finding the jekyll-search.js node module

### ISSUE THREAD

**Issue by twhite96** [christian-fei/Simple-Jekyll-Search#66]
I run jekyll build, jekyll serve, but it doesn't find the module and the search doesn't work. My repo is listed as twhite96.

I don't exactly know what is happening here or if I've done it right. Noob with Jekyll.

Any help would be appreciated.

**Comment by christian-fei** [comment]
Hello,
thanks for reporting and for using Simple Jekyll Search!

I am trying to debug it locally :)

**Comment by twhite96** [comment]
@christian-fei let me know what you find

**Comment by christian-fei** [comment]
Hello @twhite96 ,

did manage to make it work?

**Comment by daviddarnes** [comment]
@twhite96 is the website in question this one? https://tiffanywhite.tech/search/

Because it appears to be working fine now, I guess everything is ok now?

**Comment by zzpreneur** [comment]
I'm having the same issue. I tried running `jekyll build` and `jekyll serve` but it didn't work. Also, tried moving the folder into my JS folder. It loaded however, the following error appeared `ReferenceError: require is not defined`. I do I need to use browerify or webpack for this?
