### ISSUE TITLE
Search in all collections

### ISSUE THREAD

**Issue by claudiomateluna** [christian-fei/Simple-Jekyll-Search#68]
Hi there more a comment that an issue, i do it because i cost me a lot to find the answer...

if you want to use this search to look uppon all collection items you only need to change the posts for documents it always better with an example...

this is what you have...

---
---
[
  {% for post in site.posts %}
    {
      "title"    : "{{ post.title | escape }}",
      "category" : "{{ post.category }}",
      "tags"     : "{{ post.tags | array_to_sentence_string }}",
      "url"      : "{{ site.baseurl }}{{ post.url }}",
      "date"     : "{{ post.date }}"
    } {% unless forloop.last %},{% endunless %}
  {% endfor %}
]

**for search in all collections use this..**

---
---
[
  {% for post in site.documents %}
    {
      "title"    : "{{ post.title | escape }}",
      "category" : "{{ post.category }}",
      "tags"     : "{{ post.tags | array_to_sentence_string }}",
      "url"      : "{{ site.baseurl }}{{ post.url }}",
      "date"     : "{{ post.date }}"
    } {% unless forloop.last %},{% endunless %}
  {% endfor %}
]

i hope it help somebody

**Comment by christian-fei** [comment]
Thank you! I will close this for cleanliness and reference this issue in the README :)

**Comment by claudiomateluna** [comment]
ok
