### ISSUE TITLE
Add the minified in the bower

### ISSUE THREAD

**Issue by williamcanin** [christian-fei/Simple-Jekyll-Search#69]
Could you minify the "jekyll-search.js" file and make it available at "bower.json"?
Like this:

  "ignore": [
    "*",
   "!dest/jekyll-search.min.js",
   "!dest/jekyll-search.js",
    "!README.md"
  ],

Thank you :)

**Comment by daviddarnes** [comment]
hey @williamcanin, you can actually control the files you bring into a project from a bower dependency by using main-bower-files https://www.npmjs.com/package/main-bower-files#overrides-options The overrides options should allow you to select the minified version

**Comment by christian-fei** [comment]
Hello @williamcanin ,
did you managed to solve the problem you found?

Thanks @daviddarnes for helping out 🔝  :)

**Comment by williamcanin** [comment]
Hello @christian-fei .
Yes, that friend (@daviddarnes ) gave me a light.
Thank you very much, congratulations for the project. :)

**Comment by christian-fei** [comment]
Thank you :)
