### ISSUE TITLE
The demo seems to be down

### ISSUE THREAD

**Issue by AdityaAnand1** [christian-fei/Simple-Jekyll-Search#71]
http://christian-fei.github.io/Simple-Jekyll-Search/ is 404ing

**Comment by christian-fei** [comment]
Hello, thanks for reporting this issue.
Will try to fix it asap

**Comment by XhmikosR** [comment]
@christian-fei: what's needed for this to work again?

**Comment by christian-fei** [comment]
The new URL is: https://christian-fei.github.io/Simple-Jekyll-Search/

I updated the repo description, I would be glad if you could update it where needed please :)
