### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by midzer** [christian-fei/Simple-Jekyll-Search#74]
Hi.
Current /dest/ build is broken due required Templater.js, Repository.js, JSONLoader.js and OptionsValidator.js are not included.
This explains the new ultra tiny build size, too :)

Happy easter,
midzer

**Comment by christian-fei** [comment]
Hello, I will look into this. Thanks a lot for reporting :) 🐣

**Comment by paulrobertlloyd** [comment]
Just upgraded to the latest version, and seeing the same error. Any news? Thanks!

**Comment by daviddarnes** [comment]
I don't want to steal away users of this tool, it's done well for me in the past. However [I've created an alternative using the fetch() API](https://github.com/daviddarnes/alembic/blob/master/_includes/site-search.html#L14-L56) and a [custom json template](https://github.com/daviddarnes/alembic/blob/master/assets/search.json) if anyone is interested? You'll need the [fetch.js polyfill from GitHub](https://github.com/github/fetch) for older browsers

**Comment by paulrobertlloyd** [comment]
@daviddarnes Oooh, nice! I like your implementation _a lot_, so now using it instead. Thanks!

**Comment by daviddarnes** [comment]
@paulrobertlloyd you're very welcome! Thanks for the praise! Credit to Wes Bos who screencasted a filter demo using fetch, which inspired me to do this

**Comment by davidawad** [comment]
yeah this bug doesn't seem like it's going to be fixed :/

**Comment by XhmikosR** [comment]
@christian-fei: this can be closed.
