### ISSUE TITLE
Uncaught ReferenceError: SimpleJekyllSearch is not defined

### ISSUE THREAD

**Issue by realware-it** [christian-fei/Simple-Jekyll-Search#78]
Hello

I'm getting: Uncaught ReferenceError: SimpleJekyllSearch is not defined

Anyone else experiencing this?

Trying to debug the issue but still not solved:

![immagine](https://user-images.githubusercontent.com/10340551/29493301-cd5b406c-8593-11e7-8c57-fc1208b56af7.png)

![immagine](https://user-images.githubusercontent.com/10340551/29493340-243371b6-8594-11e7-8a27-fd6f51950bcd.png)

![immagine](https://user-images.githubusercontent.com/10340551/29493332-118fba06-8594-11e7-96a3-870cdb421427.png)

**Comment by XhmikosR** [comment]
Seems the src files are not being compiled anymore.

/CC @christian-fei

**Comment by christian-fei** [comment]
@XhmikosR @realware-it hello,
a new version has been published that should fix the problem.
Thanks for reporting,

Christian

**Comment by XhmikosR** [comment]
Thanks! BTW the other 2 PRs can be merged too.

**Comment by realware-it** [comment]
Thank you!

**Comment by XhmikosR** [comment]
@christian-fei: this can be closed.

**Comment by Sylhare** [comment]
Hi @christian-fei 

I have the same issue with v1.5.0 and v1.6.0. I have v1.4.1 and it is working with it. I tried the file in the example and dest folder but none of them worked.
