### ISSUE TITLE
Load json file when the input has focus

### ISSUE THREAD

**Issue by XhmikosR** [christian-fei/Simple-Jekyll-Search#85]
Currently it seems that the json file is retrieved on page load via an XHR.

I think it would be better to make the XHR when the input is focused, i.e the user intends to do a search.

**Comment by christian-fei** [comment]
I think it's useful to have the json file loaded on page load, since it's so small, and the intention is to use the search right away, not to wait and then to search. (probably in the meantime I would have already forgotten what I was looking for) 

:)

wdyt?

**Comment by XhmikosR** [comment]
Well, as you say, if it's small, then you wouldn't have to wait, after you enter the search form. So why penalize every visitor even if they don't intend to search?

Also, the json can become pretty big, so this saves time from the initial page load.

**Comment by christian-fei** [comment]
@XhmikosR good point.

I just found https://bevacqua.github.io/horsey/ which actually has implemented what we are looking for.
Maybe we could take a look and take inspiration from there

**Comment by christian-fei** [comment]
starting from here I got to horsey: https://www.npmjs.com/package/fuzzysearch

**Comment by christian-fei** [comment]
gonna close this for now @XhmikosR

**Comment by XhmikosR** [comment]
Please reopen this. It's a valid request.

**Comment by biocross** [comment]
@XhmikosR You can always do something like this, in which you can load the JSON yourself on demand, and then initialise search:

```
$.getJSON("/search.json", function (data) {
            SimpleJekyllSearch({
                searchInput: document.querySelector('#search-input'),
                resultsContainer: document.querySelector('.post-list'),
                json: data,
                searchResultTemplate: template
            });
        });
```

I'm using jQuery AJAX to load the JSON in this code, but plain JS will work just as well.

**Comment by XhmikosR** [comment]
@biocross: I'm aware how I can achieve this myself. My point is, this should be a baked in option, because it improves performance.

**Comment by christian-fei** [comment]
@XhmikosR if you want you can do a PR so that we can merge the new option

**Comment by XhmikosR** [comment]
You know I'd do it, but limited time. The request is valid though.

**Comment by XhmikosR** [comment]
Was this implemented?

**Comment by christian-fei** [comment]
nope, just cleaning up old issues

**Comment by christian-fei** [comment]
Since it's a request, we would need a PR. The discussion was interesting on this issue, but i don't think this is really a blocking issue.
The search.json file is loaded async, is relatively small, and in my opinion it is fine to close the issue

I archived it since it's been months nobody was "burdened" by this issue.

I am open for future PRs, or even rewrites

**Comment by XhmikosR** [comment]
As you wish. This is totally bad practice.
