### ISSUE TITLE
Exclude certain json values?

### ISSUE THREAD

**Issue by daviddarnes** [christian-fei/Simple-Jekyll-Search#9]
I've implemented the plugin and it's working perfectly, however I've noticed it's searching the url content in the json file. Some of the pages in my Jekyll site are nested, which means they come up in the results for top level pages.

Could an option be made to exclude or omit them?

exclude: url, …

**Comment by daviddarnes** [comment]
Was this feature added?

**Comment by christian-fei** [comment]
i'm working on it :)

**Comment by daviddarnes** [comment]
Okie doke!

**Comment by christian-fei** [comment]
Not sure if it will work, could you please try it and improve it if you have time (also to see if it what you intended?).

https://github.com/christian-fei/Simple-Jekyll-Search/releases/tag/1.0.5

**Comment by daviddarnes** [comment]
@christian-fei if I can find time I will, currently quite swamped at the moment. When the time comes I'll try it on the site I'm using it for with a local instance.

**Comment by christian-fei** [comment]
Awesome, very much appreciated!
