### ISSUE TITLE
How to convert {date} to other format?

### ISSUE THREAD

**Issue by cecilialee** [christian-fei/Simple-Jekyll-Search#94]
I'm trying to show the `{date}` result in the `#results-container` by adding it into the template.

However, the displayed date is formatted as such: **2017-10-20 00:00:00 +0800**.

How can I convert the display format to be like **20 Oct 2017**?

Thanks!

Here is my jekyll site:
https://cecilialee.github.io/

![screenshot](https://user-images.githubusercontent.com/8072787/33522592-2bee3906-d82b-11e7-9dd3-741ca92a26a3.png)

**Comment by christian-fei** [comment]
Hello,
did you manage to resolve the issue?

**Comment by XhmikosR** [comment]
Just change the date format you are using to generate your json file.

See http://alanwsmith.com/jekyll-liquid-date-formatting-examples

Untested but you want something like

```
...
"date" : "{{ post.date | date_to_string }}"
...
```

**Comment by christian-fei** [comment]
Hey @cecilialee , did you manage to get it working perhaps?
