### ISSUE TITLE
Update gh-pages branch with current version

### ISSUE THREAD

**Issue by Sylhare** [christian-fei/Simple-Jekyll-Search#95]
Hi @christian-fei,

I see that the gh-pages in running a 2 years old version of Simple Jekyll Search. It would be nice to have it updated to test the new features. :smiley: 

Thanks.

**Comment by christian-fei** [comment]
hey  @Sylhare, gonna spend some time to get it up to date in the next days

**Comment by christian-fei** [comment]
Just updated the [example blog](https://christian-fei.github.io/Simple-Jekyll-Search/) with the latest version.

Cheers @Sylhare :)
