### ISSUE TITLE
Trigger search with JavaScript

### ISSUE THREAD

**Issue by JunShern** [christian-fei/Simple-Jekyll-Search#98]
Hi!

First of all, thank you for the wonderful library, I am hoping to using it on a website I am currently building.

I want to have a feature where a user can click on a button (imagine tag or category buttons beneath the text input), and that button automatically populates the search box with the corresponding tag name, and performs the search.

I have managed to achieve the first part of it by simply setting the search input's value to my desired text, and then I tried to trigger a key-up event but unfortunately this doesn't seem to trigger the search.

```javascript
function tagButtonClick(text) {
    document.getElementById('search-input').value = text;
    $('#search-input').trigger(jQuery.Event('keyup', {which: 65}));
}
```

Any idea how I can achieve the effect I want?

**Comment by christian-fei** [comment]
Hello @JunShern ! Thanks for getting in touch :)

Could you try with the keycode `13` please?
Else any of the other keys listed [here](https://github.com/christian-fei/Simple-Jekyll-Search/blob/master/src/index.js#L121)

Let me know if you got it working or need more support.

PS: out of interest, I would love to see the website with Simple-Jekyll-Search in action :)

**Comment by JunShern** [comment]
Hi @christian-fei , thanks for the quick reply! I tried
```javascript
$('#search-input').trigger(jQuery.Event('keyup', {which: 13}));
```
and
```javascript
$('#search-input').trigger(jQuery.Event('keyup', {keycode: 13}));
```
as well, neither made a difference.

**Comment by christian-fei** [comment]
@JunShern gonna spend some time it in the next days

**Comment by christian-fei** [comment]
let me know if you find also a possible solution that fits your use case

**Comment by christian-fei** [comment]
Actually, 
@JunShern you can do the following to trigger the search programmatically:

```
      window.simpleJekyllSearch = new SimpleJekyllSearch({
        searchInput: document.getElementById('search-input'),
        resultsContainer: document.getElementById('results-container'),
        json: '{{ site.baseurl }}/search.json',
        searchResultTemplate: '<li><a href="{url}" title="{desc}">{title}</a></li>',
        noResultsText: 'No results found',
        limit: 10,
        fuzzy: false,
        exclude: ['Welcome']
      })
      setTimeout(() => {
        window.simpleJekyllSearch.search('t')
      }, 2000)
```

**Comment by christian-fei** [comment]
Hope this helps :)

**Comment by christian-fei** [comment]
I need to add this to the readme..

**Comment by christian-fei** [comment]
added: https://github.com/christian-fei/Simple-Jekyll-Search#returns--search-

**Comment by JunShern** [comment]
Yes that does do what I wanted, thank you so much!! 

One thing though, when I call the search using `window.simpleJekyllSearch.search(text)` multiple times, the results get appended instead of starting afresh - Ahhh, I can see that you [just updated the search function](https://github.com/christian-fei/Simple-Jekyll-Search/commit/cdc8fa3898ff25d5edd1ab4e329d3e0790708c06) to call `emptyResultsContainer()`, which should fix the problem. Looks like I'll just have to update to the latest version and that'll be perfect now. 

Thanks again, and great work! :smiley:

**Comment by JunShern** [comment]
By the way, to answer your question, I'm using your library on my new story-sharing website, [Kuali](https://github.com/kualistories/kualistories.github.io). It's still under construction and there isn't much information yet, but I hope to have it up and running in a month or two. Your library definitely helps!

**Comment by christian-fei** [comment]
Hey @JunShern , `v1.6.3` should fix the problem!
Thank you
